server:
  port: 8081

spring:
  application:
    name: REST_Products_DB_API
  datasource:
    url: jdbc:postgresql://192.168.1.104:5432/product
    username: restuser
    password: restpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update